language: python
python:
        - "3.6"
        - "3.6-dev"
        - "3.7"
        - "3.7-dev"
os:
        - linux
          #- osx  # To aim FreeBSD, currently broken due to missing packages
dist: xenial
env:
        - DJANGO_VERSION=2.1.4
        - DJANGO_VERSION=2.1.0
        - DJANGO_VERSION=2.1.5
        - DJANGO_Version=2.1.7
install:
        - pip install Django==$DJANGO_VERSION markdown MarkdownSuperscript MarkdownSubscript
        - pip install pyembed-markdown django_extensions pillow
        - pip install markdown-checklist reportlab qrcode django-email-extras
        - pip install django-helpdesk django-bootstrap4 django-nose coverage
script:
        - cd c3shop && python3 manage.py test
