# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatarMedia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontpage.Media'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
