# Generated by Django 2.2.4 on 2019-08-15 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_version2database'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=15000)),
                ('primary_reservation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontpage.GroupReservation')),
            ],
        ),
        migrations.AddField(
            model_name='articlerequested',
            name='SRID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontpage.SubReservation'),
        ),
    ]
