# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0002_auto_20170701_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='flashImage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontpage.Media'),
        ),
    ]
