# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-05 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0003_auto_20171005_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='chestsize',
            field=models.IntegerField(default=0, help_text="This field defines the unique chest size of the article. If it's 0 it willdefault to the chest size defined in the settings."),
            preserve_default=False,
        ),
    ]
