# Generated by Django 2.1.3 on 2018-11-19 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0004_article_chestsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('key', models.CharField(help_text='The key sequence', max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='groupreservation',
            name='responsiblePerson',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mustChangePassword',
            field=models.BooleanField(default=False, help_text='If true the user is required to change the password on next login'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pgp_keyfingerprint',
            field=models.CharField(default='', max_length=16384),
        ),
        migrations.AlterField(
            model_name='article',
            name='flashImage',
            field=models.ForeignKey(null=True, on_delete=None, to='frontpage.Media'),
        ),
        migrations.AlterField(
            model_name='mediaupload',
            name='MID',
            field=models.ForeignKey(on_delete=None, to='frontpage.Media'),
        ),
        migrations.AlterField(
            model_name='mediaupload',
            name='UID',
            field=models.ForeignKey(on_delete=None, to='frontpage.Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='createdByUser',
            field=models.ForeignKey(on_delete=None, to='frontpage.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='authuser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dect',
            field=models.IntegerField(help_text='This is the DECT number that will be displayed on the printed orders.'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='changedByUser',
            field=models.ForeignKey(on_delete=None, to='frontpage.Profile'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(help_text='The user who owns the key', on_delete=django.db.models.deletion.CASCADE, to='frontpage.Profile'),
        ),
    ]
