# Generated by Django 2.1.5 on 2019-01-11 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0005_auto_20181119_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(help_text='The user who owns the key', on_delete=django.db.models.deletion.DO_NOTHING, to='frontpage.Profile'),
        ),
        migrations.AlterField(
            model_name='article',
            name='addedByUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontpage.Profile'),
        ),
        migrations.AlterField(
            model_name='article',
            name='flashImage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontpage.Media'),
        ),
        migrations.AlterField(
            model_name='articlemedia',
            name='AID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontpage.Article'),
        ),
        migrations.AlterField(
            model_name='articlemedia',
            name='MID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontpage.Media'),
        ),
        migrations.AlterField(
            model_name='articlerequested',
            name='AID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontpage.Article'),
        ),
        migrations.AlterField(
            model_name='articlerequested',
            name='RID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontpage.GroupReservation'),
        ),
        migrations.AlterField(
            model_name='groupreservation',
            name='createdByUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontpage.Profile'),
        ),
        migrations.AlterField(
            model_name='mediaupload',
            name='MID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontpage.Media'),
        ),
        migrations.AlterField(
            model_name='mediaupload',
            name='UID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontpage.Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='createdByUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontpage.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatarMedia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontpage.Media'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='changedByUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontpage.Profile'),
        ),
    ]
