# Generated by Django 2.1.5 on 2019-01-11 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0006_auto_20190111_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(help_text='The display name of the article group', max_length=150)),
                ('group_flash_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontpage.Media')),
            ],
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(help_text='This is the headline of the message', max_length=250)),
                ('text', models.CharField(help_text='This is the body of the message', max_length=16384)),
            ],
        ),
        migrations.AddField(
            model_name='groupreservation',
            name='submitted',
            field=models.BooleanField(default=False, help_text='This determines if a reservation is still under constructionor already submitted'),
        ),
        migrations.AddField(
            model_name='profile',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='If True the user must change the password on next login'),
        ),
        migrations.AddField(
            model_name='profile',
            name='next_login_announcement',
            field=models.CharField(help_text='If not null it will be displayed on next login', max_length=16384, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_allowed_reservations',
            field=models.SmallIntegerField(default=1, help_text='This specifies the amount of reservations a user isallowed to add, default is 1, -1 means unlimited'),
        ),
        migrations.AddField(
            model_name='article',
            name='group',
            field=models.ForeignKey(help_text='This will be null if the articledoesnt belong to a group', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontpage.ArticleGroup'),
        ),
    ]
