# Generated by Django 2.1.5 on 2019-03-12 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0007_auto_20190111_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='underConstruction',
            field=models.BooleanField(default=False, help_text='If true the article is still under construction'),
        ),
        migrations.AlterField(
            model_name='article',
            name='group',
            field=models.ForeignKey(help_text='This will be null if the article doesnt belong to a group', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontpage.ArticleGroup'),
        ),
        migrations.AlterField(
            model_name='groupreservation',
            name='submitted',
            field=models.BooleanField(default=False, help_text='This determines if a reservation is still under construction or already submitted'),
        ),
    ]
